export const PROVIDER_LIST_REQUEST = 'PROVIDER_LIST_REQUEST'
export const PROVIDER_LIST_SUCCESS = 'PROVIDER_LIST_SUCCESS'
export const PROVIDER_LIST_FAIL = 'PROVIDER_LIST_FAIL'

export const PROVIDER_DATA_REQUEST = 'PROVIDER_DATA_REQUEST'
export const PROVIDER_DATA_SUCCESS = 'PROVIDER_DATA_SUCCESS'
export const PROVIDER_DATA_FAIL = 'PROVIDER_DATA_FAIL'